# Generated by Django 5.1.4 on 2024-12-19 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='linkedin_activity',
        ),
        migrations.AddField(
            model_name='account',
            name='competitors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='customers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firebase_id'], name='users_firebas_d15ace_idx'),
        ),
    ]
