# Generated by Django 5.1.4 on 2025-01-02 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_tenant_alter_lead_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('scope', models.CharField(choices=[('global', 'Global'), ('tenant', 'Tenant Specific'), ('user', 'User Specific')], default='global', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='app.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configs',
                'indexes': [models.Index(fields=['key'], name='configs_key_2a48e5_idx'), models.Index(fields=['scope'], name='configs_scope_6527ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'tenant', 'user', 'key'), name='unique_config_per_scope')],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='app.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings',
                'indexes': [models.Index(fields=['key'], name='settings_key_e0b620_idx'), models.Index(fields=['tenant', 'user'], name='settings_tenant__2b8d0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'key'), name='unique_setting_per_scope')],
            },
        ),
    ]
