# Generated by Django 5.1.4 on 2025-01-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_config_settings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['account'], name='leads_account_303698_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_by'], name='leads_created_dee243_idx'),
        ),
    ]
