# Generated by Django 5.1.4 on 2025-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lead_leads_account_303698_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant'], name='accounts_tenant__92607e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_by'], name='accounts_created_aa7c53_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant'], name='leads_tenant__09170a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant'], name='products_tenant__8bba44_idx'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['tenant'], name='settings_tenant__e259df_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant'], name='users_tenant__d262cd_idx'),
        ),
    ]
