# Generated by Django 5.1.4 on 2025-01-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_accounts_tenant__92607e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.TextField(null=True),
        ),
    ]
