# Generated by Django 5.1.4 on 2025-01-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
