# Generated by Django 5.1.4 on 2025-01-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_account_enrichment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enrichment_data',
            field=models.JSONField(blank=True, help_text='Stores enrichment specific data like fit score, persona match etc', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually Added'), ('enrichment', 'Generated via Enrichment'), ('import', 'Imported from File')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='suggestion_status',
            field=models.CharField(choices=[('suggested', 'AI Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual', 'Manually Added')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountenrichmentstatus',
            name='enrichment_type',
            field=models.CharField(choices=[('company_info', 'Company Information'), ('potential_leads', 'Potential Leads for a particular Account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='leads_source_805dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['suggestion_status'], name='leads_suggest_b422ca_idx'),
        ),
    ]
