# Generated by Django 5.1.4 on 2025-01-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lead_enrichment_data_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountenrichmentstatus',
            name='completion_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountenrichmentstatus',
            name='enrichment_type',
            field=models.CharField(choices=[('company_info', 'Company Information'), ('generate_leads', 'Potential Leads for a particular Account'), ('lead_linkedin_research', 'Lead Information from LinkedIn and other sources')], max_length=50),
        ),
    ]
