# Generated by Django 5.1.4 on 2025-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_accountenrichmentstatus_completion_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='playbook_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
