# Generated by Django 5.1.4 on 2025-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_playbook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_technology_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
