# Generated by Django 5.1.4 on 2025-03-04 09:37

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_account_full_technology_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_score_7739f8_idx',
        ),
        migrations.AlterField(
            model_name='accountenrichmentstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-score'], name='leads_score_80ceed_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=django.contrib.postgres.indexes.GinIndex(fields=['enrichment_data'], name='lead_enrichment_data_idx'),
        ),
    ]
