# Generated by Django 5.1.4 on 2025-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recent_events',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
