# Generated by Django 5.1.4 on 2025-03-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_accountenrichmentstatus_enrichment_type_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountcustomcolumnvalue',
            new_name='account_cus_status_31cd18_idx',
            old_name='app_account_status_4f1cf0_idx',
        ),
        migrations.RenameIndex(
            model_name='accountcustomcolumnvalue',
            new_name='account_cus_generat_a0ff09_idx',
            old_name='app_account_generat_8a427d_idx',
        ),
        migrations.RenameIndex(
            model_name='accountcustomcolumnvalue',
            new_name='account_cus_account_856d79_idx',
            old_name='app_account_account_093b01_idx',
        ),
        migrations.RenameIndex(
            model_name='accountenrichmentstatus',
            new_name='account_enr_account_b757ef_idx',
            old_name='app_account_account_615bca_idx',
        ),
        migrations.RenameIndex(
            model_name='accountenrichmentstatus',
            new_name='account_enr_status_34f3d6_idx',
            old_name='app_account_status_022c3e_idx',
        ),
        migrations.RenameIndex(
            model_name='accountenrichmentstatus',
            new_name='account_enr_last_at_5af37b_idx',
            old_name='app_account_last_at_08892a_idx',
        ),
        migrations.RenameIndex(
            model_name='customcolumn',
            new_name='custom_colu_tenant__c8b3f7_idx',
            old_name='app_customc_tenant__da5eb1_idx',
        ),
        migrations.RenameIndex(
            model_name='customcolumn',
            new_name='custom_colu_entity__518003_idx',
            old_name='app_customc_entity__0d7819_idx',
        ),
        migrations.RenameIndex(
            model_name='customcolumn',
            new_name='custom_colu_is_acti_15a955_idx',
            old_name='app_customc_is_acti_ee54f6_idx',
        ),
        migrations.RenameIndex(
            model_name='leadcustomcolumnvalue',
            new_name='lead_custom_status_ddf9e7_idx',
            old_name='app_leadcus_status_7c674e_idx',
        ),
        migrations.RenameIndex(
            model_name='leadcustomcolumnvalue',
            new_name='lead_custom_generat_646320_idx',
            old_name='app_leadcus_generat_6f7f52_idx',
        ),
        migrations.RenameIndex(
            model_name='leadcustomcolumnvalue',
            new_name='lead_custom_lead_id_a1e366_idx',
            old_name='app_leadcus_lead_id_f1ca9d_idx',
        ),
        migrations.AlterModelTable(
            name='accountcustomcolumnvalue',
            table='account_custom_column_values',
        ),
        migrations.AlterModelTable(
            name='accountenrichmentstatus',
            table='account_enrichment_status',
        ),
        migrations.AlterModelTable(
            name='customcolumn',
            table='custom_columns',
        ),
        migrations.AlterModelTable(
            name='leadcustomcolumnvalue',
            table='lead_custom_column_values',
        ),
    ]
