# Generated by Django 5.1.4 on 2025-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_app_account_status_4f1cf0_idx_account_cus_status_31cd18_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustomcolumnvalue',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadcustomcolumnvalue',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
