# Generated by Django 5.1.4 on 2025-03-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_accountcustomcolumnvalue_rationale_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customcolumn',
            name='custom_colu_tenant__c8b3f7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customcolumn',
            unique_together={('tenant', 'entity_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='customcolumn',
            index=models.Index(fields=['tenant'], name='custom_colu_tenant__6c9357_idx'),
        ),
        migrations.RemoveField(
            model_name='customcolumn',
            name='product',
        ),
    ]
