# Generated by Django 5.1.4 on 2025-04-28 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_customcolumn_custom_colu_tenant__c8b3f7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColumnDependency',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dependent_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='app.customcolumn')),
                ('required_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='app.customcolumn')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tenant')),
            ],
            options={
                'db_table': 'custom_column_dependencies',
                'unique_together': {('dependent_column', 'required_column')},
            },
        ),
    ]
