# Generated by Django 5.1.4 on 2025-05-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_customcolumndependency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customcolumn',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customcolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'entity_type', 'name'), name='unique_active_custom_column'),
        ),
    ]
