apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: django-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 8000
    type: HTTP
    requestPath: /api/v2/health/status/