apiVersion: apps/v1
kind: Deployment
metadata:
  name: userport-django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userport-django-app
  template:
    metadata:
      labels:
        app: userport-django-app
    spec:
      serviceAccountName: userport-ksa
      containers:
      - name: userport-django-app
        image: gcr.io/omega-winter-431704-u5/userport-django-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: GUNICORN_TIMEOUT
          value: "120"
        - name: USERPORT_DEV_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: USERPORT_DEV_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/v2/health/ready/
            port: 8000
          initialDelaySeconds: 90
          timeoutSeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v2/health/status/
            port: 8000
          initialDelaySeconds: 90
          timeoutSeconds: 10
          periodSeconds: 15
          failureThreshold: 3