apiVersion: v1
kind: Service
metadata:
  name: userport-django-service
  annotations:
    cloud.google.com/backend-config: '{"default": "django-backendconfig"}'
spec:
  type: NodePort
  selector:
    app: userport-django-app
  ports:
    - port: 80
      targetPort: 8000