# cloudbuild.yaml
steps:
# Build the container image with build args
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--platform=linux/amd64',
    '-f', './api/django_app/Dockerfile',
    '--build-arg', 'USERPORT_DEBUG=${_USERPORT_DEBUG}',
    '--build-arg', 'USERPORT_DEV_DB_USERNAME=${_USERPORT_DEV_DB_USERNAME}',
    '--build-arg', 'USERPORT_DEV_DB_PASSWORD=${_USERPORT_DEV_DB_PASSWORD}',
    '--build-arg', 'ALLOWED_HOSTS=${_ALLOWED_HOSTS}',
    '--build-arg', 'GUNICORN_WORKERS=${_GUNICORN_WORKERS}',
    '--build-arg', 'GUNICORN_TIMEOUT=${_GUNICORN_TIMEOUT}',
    '--build-arg', 'PORT=${_PORT}',
    '-t', 'gcr.io/$PROJECT_ID/userport-django-app:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/userport-django-app:latest',
    './api/django_app'
  ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/userport-django-app:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/userport-django-app:latest']

# Deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=api/django_app/
  - --location=us-west1
  - --cluster=userport-service-prod
  - --image=gcr.io/$PROJECT_ID/userport-django-app:$COMMIT_SHA

substitutions:
  _USERPORT_DEBUG: '0'
  _ALLOWED_HOSTS: '*'
  _GUNICORN_WORKERS: '4'
  _GUNICORN_TIMEOUT: '120'
  _PORT: '8000'


options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'gcr.io/$PROJECT_ID/userport-django-app:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/userport-django-app:latest'