steps:
  # Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/omega-winter-431704/prefect-server', '.']

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/omega-winter-431704/prefect-server']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'prefect-server'
      - '--image=gcr.io/omega-winter-431704/prefect-server'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--add-cloudsql-instances=omega-winter-431704:us-central1:prefect-db'
      - '--set-secrets=PREFECT_DB_PASSWORD=prefect-db-password:latest'

images:
  - 'gcr.io/omega-winter-431704/prefect-server'

options:
  logging: CLOUD_LOGGING_ONLY