steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/prefect-server:latest',
      '-f', 'workers/scripts/prefect_server/Dockerfile',
      '.'
    ]

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', 'gcr.io/$PROJECT_ID/prefect-server:latest']
    waitFor: ['build']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'prefect-server',
      '--image=gcr.io/$PROJECT_ID/prefect-server:$COMMIT_SHA',
      '--platform=managed',
      '--region=us-central1',
      '--allow-unauthenticated',
      '--memory=1Gi',
      '--cpu=1',
      '--min-instances=1',
      '--add-cloudsql-instances=$PROJECT_ID:us-central1:prefect-db',
      '--set-secrets=PREFECT_DB_PASSWORD=prefect-db-password:latest'
    ]
    waitFor: ['push-latest']

timeout: 1800s

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

images:
  - 'gcr.io/$PROJECT_ID/prefect-server:latest'