apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userport-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: userport-prod
    networking.gke.io/managed-certificates: managed-cert-v5
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: "app.userport.ai"
      http:
        paths:
          - path: /api/v2/
            pathType: Prefix
            backend:
              service:
                name: userport-django-service
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: userport-django-service
                port:
                  number: 80