# Following the official guide: https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#create-ingress.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userport-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: react-service
            port:
              number: 80
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: flask-api-service
            port:
              number: 80