# Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#setting_up_a_google-managed_certificate.
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert-v5
spec:
  domains:
    # To make updates to domains in the future, create a new certificate manifest with existing and 
    # the new domains, add the new certificate manifest to the App's Ingress manifest and once provisioned, delete
    # the old certificate and associated manifest.
    - app.userport.ai
