"""
Django settings for userport project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

if os.path.exists('.env'):
    load_dotenv('.env')
elif os.path.exists('.dev.env'):
    load_dotenv('.dev.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

WORKER_API_BASE_URL = os.environ.get('WORKER_API_BASE_URL')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sy*-3-211i9@b#il3bet@y$@ci!khoejh_$l6t^d@1*9u!kum^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('USERPORT_DEBUG', '0') == '1'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.TenantMiddleware',
    'google.cloud.logging_v2.handlers.middleware.RequestMiddleware',  # Reference: https://cloud.google.com/python/docs/reference/logging/latest/web-framework-integration.
]

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = DEBUG  # This will allow all origins in development
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-id'
]

AUTH_USER_MODEL = 'app.User'

FIREBASE_AUTH_EXEMPT_PATHS = [
    '/api/v2/internal/enrichment-callback/'
]

# Rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'app.middleware.FirebaseAuthMiddleware'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_EXEMPT_PATHS': [
        '/api/v2/internal/enrichment-callback/'
    ]
    # TODO(Sowrabh) 'EXCEPTION_HANDLER': ''
}

ROOT_URLCONF = 'userport.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'userport.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

dbusername = os.environ.get('USERPORT_DEV_DB_USERNAME')
dbpassword = os.environ.get('USERPORT_DEV_DB_PASSWORD')

if not dbusername or not dbpassword:
    import logging
    logger = logging.getLogger('django.db.backends')
    logger.error(f"Database credentials not properly set: username={'present' if dbusername else 'missing'}, password={'present' if dbpassword else 'missing'}")


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'userport',
        'USER': dbusername,
        'PASSWORD': dbpassword,
        'HOST': "127.0.0.1",
        'PORT': "5432",
        'ATOMIC_REQUESTS': True,
        'DEFAULT_SCHEMA': 'public'
    }
}

if os.path.exists('.dev.env'):
    # Local env.
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
            },
        },
        'loggers': {
            'permissions': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.db.backends': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'django.db.backends.schema': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'django.db.models': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.urls': {
                'handlers': ['console'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'health': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True,
            }
        },
        'root': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    }
else:
    import logging
    import logging.config
    import google.cloud.logging
    from google.cloud.logging.handlers import CloudLoggingHandler
    from google.cloud.logging_v2.handlers.transports.sync import SyncTransport

    # Production logging configuration for GCP
    client = google.cloud.logging.Client()
    env = "production"

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'json': {
                'class': 'pythonjsonlogger.jsonlogger.JsonFormatter',
                'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
            },
        },
        'handlers': {
            'cloudlogging': {
                'class': 'google.cloud.logging.handlers.CloudLoggingHandler',
                'client': client,
                'formatter': 'json',
                'labels': {
                    'environment': env,
                    'application': 'userport-django-app'
                },
                'name': 'django_app'
            },
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'json'
            }
        },
        'loggers': {
            'permissions': {
                'handlers': ['cloudlogging', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.db.backends': {
                'handlers': ['cloudlogging', 'console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'django.db.backends.schema': {
                'handlers': ['cloudlogging', 'console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'django.db.models': {
                'handlers': ['cloudlogging', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.urls': {
                'handlers': ['cloudlogging', 'console'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'health': {
                'handlers': ['cloudlogging', 'console'],
                'level': 'WARNING',
                'propagate': True,
            },
            'django.security': {
                'handlers': ['cloudlogging', 'console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'app': {  # Main app logger
                'handlers': ['cloudlogging', 'console'],
                'level': 'DEBUG',
                'propagate': True,
            }
        },
        'root': {
            'handlers': ['cloudlogging', 'console'],
            'level': 'INFO',
        },
    }

# Apply the configuration
logging.config.dictConfig(LOGGING)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
